services:
  - type: web
    name: chat-cyberpunk
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k eventlet -w 1 app:app"
    region: oregon
    plan: free
    branch: main
